# 📌 Урок: Работа с файлами
## 📖 Теоретический минимум

Текстовые файлы (.txt) - простые файлы с неструктурированным текстом

CSV (Comma-Separated Values) - табличные данные с разделителями

Excel (.xlsx, .xls) - электронные таблицы с расширенными возможностями

JSON - структурированные данные в формате ключ-значение

Бинарные файлы - изображения, PDF и другие нетекстовые форматы

# 🔹 Основные операции с файлами
Открытие/закрытие файла

Чтение данных

Запись данных

Обработка больших файлов


# 📖 Материалы

https://vkvideo.ru/video-194554202_456239677

https://vkvideo.ru/video-194554202_456239682









# 🏆 Задания

## 1️⃣ Работа с текстовыми файлами
**Задача:**
 Создать текстовый файл, записать в него str данные и прочитать обратно

In [2]:
with open("ДЗ 9 задание 1.txt", "w") as file:
    file.write("Ас-саляму алейкум ва-рахмату-Ллахи ва-баракятух")
with open("ДЗ 9 задание 1.txt", "r") as file:
    text = file.read()
    print(text)

Ас-саляму алейкум ва-рахмату-Ллахи ва-баракятух



## 2️⃣ Работа с CSV файлами

**Задача:**

Создать CSV файл с табличными данными, записать и прочитать его



In [4]:
import csv

df = [
    ['Bird','Color'],
    ["voron", "black"],
    ["snegir", "red"],
]

with open("ДЗ 9 задание 2.csv", "w", newline="", encoding="utf-8") as file:
    data = csv.writer(file)
    data.writerows(df)

with open("ДЗ 9 задание 2.csv", "r", encoding="utf-8") as file:
    data = csv.reader(file)
    for i in data:
        print(i)

['Bird', 'Color']
['voron', 'black']
['snegir', 'red']


## 3️⃣  Работа с Excel файлами
**Задача:** Создать Excel файл и прочитать данные из него

Используйте библиотеку pandas

---



In [7]:
import pandas as pd

df = [
    ["Bird", "Color"],
    ["voron", "black"],
    ["snegir", "red"],
]

df = pd.DataFrame(df)
df.to_excel("ДЗ 9 задание 3.xlsx", index=False)
print(pd.read_excel("ДЗ 9 задание 3.xlsx"))

        0      1
0    Bird  Color
1   voron  black
2  snegir    red



## 4️⃣  Чтение больших файлов по частям


**Задача:** Обработать файл построчно без загрузки в память целиком

Реализуйте чанки самостоятельно или воспользуйтесь chunk из pandas

---




In [31]:
import numpy as np
import pandas as pd


def generate_with_numpy(filename, rows=1_000, columns=6):
    data = np.random.randint(0, 1000, size=(rows, columns))
    df = pd.DataFrame(data, columns=[f"col_{i}" for i in range(columns)])
    df.to_csv(filename, index=False)
    print(f"Создан файл {filename} размером {rows} x {columns}")


# Использование
generate_with_numpy("ДЗ 9 задание 4.csv")

Создан файл ДЗ 9 задание 4.csv размером 1000 x 6


In [32]:
import pandas as pd


def process_with_pandas_chunks(file_path, chunk_size):
    for chunk in pd.read_csv(file_path, chunksize=chunk_size):
        print(chunk)


chunk_size=3
process_with_pandas_chunks("ДЗ 9 задание 4.csv", chunk_size)

   col_0  col_1  col_2  col_3  col_4  col_5
0     55      8    340    156    833    579
1    116     52      7    608    662    694
2    701    234    644    204    848    241
   col_0  col_1  col_2  col_3  col_4  col_5
3    457    766    646    302     26    192
4    211    943    226    953    213    590
5    154    342    789    458     57    613
   col_0  col_1  col_2  col_3  col_4  col_5
6    853    700    644    940    733    726
7    140    854    866    743    879    890
8    811    622    728    109    510    972
    col_0  col_1  col_2  col_3  col_4  col_5
9     221    531    123    691    457    339
10    522    207    108    625    828    455
11    318    151    417    506    980    900
    col_0  col_1  col_2  col_3  col_4  col_5
12    793    687    152    302    575    799
13    746    508    515    179    692    226
14    261    486    145    615    766    585
    col_0  col_1  col_2  col_3  col_4  col_5
15    627    991    849    450    364    592
16    698    556    54


## 5️⃣ Чтение JPEG файла
**Задача:**

Создайте изображение 21х21 пиксель в формате JPEG

Прочитайте JPEG файл в бинарном режиме

Выведете прочитанный файл как массив интенсивности пикселей

---


In [37]:
from PIL import Image
import numpy as np

# Создаем массив 21x21x3 (RGB) со случайными значениями
image_data = np.random.randint(0, 256, (21, 21, 3), dtype=np.uint8)

# Создаем изображение из массива
img = Image.fromarray(image_data, "RGB")

# Сохраняем в JPEG
img.save("ДЗ 9 задание 5_image.jpg")

ir = Image.open("ДЗ 9 задание 5_image.jpg")
arr = np.array(ir)
print(arr)

[[[ 90 194 159]
  [126 175 169]
  [129  70 118]
  ...
  [ 52  43 106]
  [105  92 171]
  [153 149 244]]

 [[ 29 100  58]
  [138 171 154]
  [ 84  41  69]
  ...
  [ 87  84 137]
  [137 131 191]
  [ 54  47 115]]

 [[125 130  76]
  [187 188 148]
  [210 203 193]
  ...
  [102 113 143]
  [145 156 176]
  [ 99  84 103]]

 ...

 [[ 65 110 143]
  [  6  36  60]
  [ 56  55  63]
  ...
  [131 118 109]
  [117 100  90]
  [ 38  14  10]]

 [[ 49 115 141]
  [ 93 153 161]
  [175 223 197]
  ...
  [ 81  78  71]
  [214 211 192]
  [105 100  78]]

 [[ 89 184 162]
  [ 35 123  81]
  [126 201 118]
  ...
  [ 50  74  38]
  [205 235 175]
  [182 219 142]]]
